version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 9001:8080
    volumes:
      - jenkins-volume:/var/jenkins_home


  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    environment:
      - sonar.jdbc.username=root
      - sonar.jdbc.password=1azerty.
      - sonar.jdbc.url=jdbc:postgresql://admin-db:3306/sonar
    ports:
      - 9002:9000
    depends_on:
      - admin-db
    networks:
      - global-network

  admin-db:
    image: postgres:latest
    container_name: admin-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1azerty.
    ports:
      - 3307:1000
    volumes:
      - admin-db-volume:/var/lib/mysql
    networks:
      - global-network

volumes:
  jenkins-volume:
  sonarqube-volume:
  admin-db-volume:

networks:
  global-network:
    external:
      name: global-network
