version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 9001:8080
    volumes:
      - jenkins-volume:/var/jenkins_home


  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 9002:9000
    links:
      - admin-db:db
    volumes:
      - sonarqube-volume
    depends_on:
      - admin-db
    networks:
      - global-network

  admin-db:
    image: mysql:latest
    container_name: admin-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1azerty.
    ports:
      - 3307:3306
    volumes:
      - admin-db-volume:/var/lib/mysql
    networks:
      - global-network

volumes:
  jenkins-volume:
  sonarqube-volume:
  admin-db-volume:

networks:
  global-network:
    name: global-network
    external: true
