version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 9001:8080
    volumes:
      - jenkins-data:/var/jenkins_home


  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    environment:
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=1azerty.
      - sonar.jdbc.url=jdbc:postgresql://admin-db/sonar
    ports:
      - 9002:9000
    depends_on:
      - admin-db
    networks:
      - global-network

  admin-db:
    image: postgres:latest
    container_name: admin-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1azerty.
      - POSTGRES_DB=sonar
    volumes:
      - goaccess-logs:/var/log
      - admin-db-data:/var/lib/postgresql/data
    networks:
      - global-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 9003:8080
    networks:
      - global-network

volumes:
  jenkins-data:
  admin-db-data:
  goaccess-logs:
  goaccess-reports:

networks:
  global-network:
    external:
      name: global-network
