version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 9001:8080
    volumes:
      - jenkins-volume:/var/jenkins_home


  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 9002:9000
    volumes:
      - sonarqube-volume

volumes:
  jenkins-volume:
  sonarqube-volume:
