# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - network


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - network

  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    ports:
      - 8081:8080
      - 5000
    volumes:
      - jenkins-volume:/var/jenkins_home
    networks:
      - network

  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - 8082:9000
    volumes:
      - sonarqube-volume:/opt/sonarqube
    networks:
      - network

  portainer:
    image: portainer/portainer:latest
    restart: always
    ports:
      - 8083:9000
    volumes:
      - portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network

  tomcat:
    image: tomcat:latest
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone='Europe/Paris'
    ports:
      - 8084:8080
    volumes:
      - tomcat-volume:/usr/local/tomcat/
    networks:
      - network

volumes:
  db-volume:
  jenkins-volume:
  sonarqube-volume:
  portainer-volume:
  tomcat-volume:

networks:
  network:
    driver: bridge
