# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'sonar'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - network


  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - network

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - '8081:8080'
      - '5000'
    volumes:
      - jenkins-volume:/var/jenkins_home
    networks:
      - network

  sonarqube:
    image: sonarqube
    restart: always
    environment:
      - sonar.jdbc.username=root
      - sonar.jdbc.password=root
      - sonar.jdbc.url=jdbc:sqlserver://localhost;databaseName=sonar
    ports:
      - "8082:9000"
    networks:
      - network


volumes:
  db-volume:
  jenkins-volume:

networks:
  network:
