version: '3.1'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - global-network

volumes:
  portainer-data:

networks:
  global-network:
    external:
      name: global-network

